DROP PROCEDURE IF EXISTS EXTRACRED;
DELIMITER $$
CREATE PROCEDURE EXTRACRED 
BEGIN
SELECT COUNT(*) as num, PRESCRIPTION.prescriptionName
FROM PRESCRIPTION, PVISITDESCRIPTION, PATIENTVISIT, PATIENT, PERSON
WHERE PRESCRIPTION.prescriptionID = PVISITDESCRIPTION.prescriptionID
  AND PVISITDESCRIPTION.visitID = PATIENTVISIT.visitID
  AND PATIENTVISIT.patientID = PATIENT.patientID
  AND PATIENT.personID = PERSON.personID
GROUP BY PRESCRIPTION.prescriptionName;
END $$
DELIMITER ;
