CREATE PROCEDURE EXTRACRED
AS
SELECT COUNT(*), PRESCRIPTION.prescriptionName
FROM PRESCRIPTION, PVISITDESCRIPTION, PATIENTVISIT, PATIENT, PERSON
WHERE PRESCRIPTION.prescriptionID = PVISITDESCRIPTION.prescriptionID
AND PVISITDESCRIPTION.visitID = PATIENTVISIT.visitID
AND PATIENTVISIT.patientID = PATIENT.patientID
AND PATIENT.personID = PERSON.personID
GROUP BY PRESCRIPTION.prescriptionName
GO;
