DROP PROCEDURE IF EXISTS EXTRACRED;
CREATE PROCEDURE EXTRACRED ()
  SELECT COUNT(*) as num, PRESCRIPTION.prescriptionName
  FROM PRESCRIPTION, PVISITDESCRIPTION, PATIENTVISIT, PATIENT, PERSON
  WHERE PRESCRIPTION.prescriptionID = PVISITDESCRIPTION.prescriptionID
    AND PVISITDESCRIPTION.visitID = PATIENTVISIT.visitID
    AND PATIENTVISIT.patientID = PATIENT.patientID
    AND PATIENT.personID = PERSON.personID
	AND PERSON.city = 'Fullerton'
  GROUP BY PRESCRIPTION.prescriptionName
  ORDER BY num DESC;

